package com.pccw.lizhihui.cmcc.data.greendao.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.pccw.lizhihui.cmcc.data.greendao.db.UserEntity;
import com.pccw.lizhihui.cmcc.data.greendao.db.DepartmentEntity;

import com.pccw.lizhihui.cmcc.data.greendao.db.UserEntityDao;
import com.pccw.lizhihui.cmcc.data.greendao.db.DepartmentEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userEntityDaoConfig;
    private final DaoConfig departmentEntityDaoConfig;

    private final UserEntityDao userEntityDao;
    private final DepartmentEntityDao departmentEntityDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userEntityDaoConfig = daoConfigMap.get(UserEntityDao.class).clone();
        userEntityDaoConfig.initIdentityScope(type);

        departmentEntityDaoConfig = daoConfigMap.get(DepartmentEntityDao.class).clone();
        departmentEntityDaoConfig.initIdentityScope(type);

        userEntityDao = new UserEntityDao(userEntityDaoConfig, this);
        departmentEntityDao = new DepartmentEntityDao(departmentEntityDaoConfig, this);

        registerDao(UserEntity.class, userEntityDao);
        registerDao(DepartmentEntity.class, departmentEntityDao);
    }
    
    public void clear() {
        userEntityDaoConfig.getIdentityScope().clear();
        departmentEntityDaoConfig.getIdentityScope().clear();
    }

    public UserEntityDao getUserEntityDao() {
        return userEntityDao;
    }

    public DepartmentEntityDao getDepartmentEntityDao() {
        return departmentEntityDao;
    }

}
