package com.pccw.lizhihui.cmcc.data.greendao.db;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import com.pccw.lizhihui.cmcc.data.greendao.db.DepartmentEntity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "DEPARTMENT_ENTITY".
*/
public class DepartmentEntityDao extends AbstractDao<DepartmentEntity, Long> {

    public static final String TABLENAME = "DEPARTMENT_ENTITY";

    /**
     * Properties of entity DepartmentEntity.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property DeptName = new Property(1, String.class, "deptName", false, "DEPT_NAME");
        public final static Property DeptCode = new Property(2, String.class, "deptCode", false, "DEPT_CODE");
        public final static Property ParentCode = new Property(3, String.class, "parentCode", false, "PARENT_CODE");
        public final static Property DeptId = new Property(4, String.class, "deptId", false, "DEPT_ID");
        public final static Property DepartmentId = new Property(5, Long.class, "departmentId", false, "DEPARTMENT_ID");
    };

    private DaoSession daoSession;

    private Query<DepartmentEntity> userEntity_DeptListQuery;

    public DepartmentEntityDao(DaoConfig config) {
        super(config);
    }
    
    public DepartmentEntityDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"DEPARTMENT_ENTITY\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"DEPT_NAME\" TEXT," + // 1: deptName
                "\"DEPT_CODE\" TEXT," + // 2: deptCode
                "\"PARENT_CODE\" TEXT," + // 3: parentCode
                "\"DEPT_ID\" TEXT," + // 4: deptId
                "\"DEPARTMENT_ID\" INTEGER);"); // 5: departmentId
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"DEPARTMENT_ENTITY\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, DepartmentEntity entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String deptName = entity.getDeptName();
        if (deptName != null) {
            stmt.bindString(2, deptName);
        }
 
        String deptCode = entity.getDeptCode();
        if (deptCode != null) {
            stmt.bindString(3, deptCode);
        }
 
        String parentCode = entity.getParentCode();
        if (parentCode != null) {
            stmt.bindString(4, parentCode);
        }
 
        String deptId = entity.getDeptId();
        if (deptId != null) {
            stmt.bindString(5, deptId);
        }
    }

    @Override
    protected void attachEntity(DepartmentEntity entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public DepartmentEntity readEntity(Cursor cursor, int offset) {
        DepartmentEntity entity = new DepartmentEntity( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // deptName
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // deptCode
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // parentCode
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4) // deptId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, DepartmentEntity entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setDeptName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setDeptCode(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setParentCode(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setDeptId(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(DepartmentEntity entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(DepartmentEntity entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "deptList" to-many relationship of UserEntity. */
    public List<DepartmentEntity> _queryUserEntity_DeptList(Long departmentId) {
        synchronized (this) {
            if (userEntity_DeptListQuery == null) {
                QueryBuilder<DepartmentEntity> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.DepartmentId.eq(null));
                userEntity_DeptListQuery = queryBuilder.build();
            }
        }
        Query<DepartmentEntity> query = userEntity_DeptListQuery.forCurrentThread();
        query.setParameter(0, departmentId);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getUserEntityDao().getAllColumns());
            builder.append(" FROM DEPARTMENT_ENTITY T");
            builder.append(" LEFT JOIN USER_ENTITY T0 ON T.\"DEPARTMENT_ID\"=T0.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected DepartmentEntity loadCurrentDeep(Cursor cursor, boolean lock) {
        DepartmentEntity entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        UserEntity userEntity = loadCurrentOther(daoSession.getUserEntityDao(), cursor, offset);
        entity.setUserEntity(userEntity);

        return entity;    
    }

    public DepartmentEntity loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<DepartmentEntity> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<DepartmentEntity> list = new ArrayList<DepartmentEntity>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<DepartmentEntity> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<DepartmentEntity> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
